name: 💡 Feature Request
description: Suggest an idea for ShopSphere
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen
      placeholder: "It would be great if..."
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which area of ShopSphere does this feature relate to?
      options:
        - User Interface
        - Shopping Cart
        - Payment System
        - Product Management
        - User Authentication
        - Admin Panel
        - Search/Filter
        - Other
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Feature Scope
      description: Which part of ShopSphere does this feature lies in or will affect?
      options:
        - Frontend
        - Backend
        - Both
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered
      placeholder: "Other approaches that might work..."

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here
      placeholder: "Any other details you'd like to share?"